Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()

src = Split("""
""")

if GetDepend(['CONFIG_REALTEK_KEY_BUTTON_8773G']):
    src += ['key_button_8773g.c']

CPPPATH = [cwd]

group = DefineGroup('key_button', src, depend = ['CONFIG_REALTEK_8773G_DEVICE'], CPPPATH = CPPPATH)

Return('group')