

from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")


if GetDepend(['CONFIG_REALTEK_ST7796_320320_8080']):
    src += ['lcd_st7796_320.c']
if GetDepend(['CONFIG_REALTEK_NV3041A_480272_QSPI']):
    src += ['nv3041A_8762D_480_272_qspi.c']
if GetDepend(['CONFIG_REALTEK_ST7796_480320_8080']):
    src += ['lcd_st7796_480_320.c']
if GetDepend(['CONFIG_REALTEK_ST77916G5_320_QSPI']):
    src += ['lcd_st77916g5_320_qspi.c']
if GetDepend(['CONFIG_REALTEK_ST7789_240240_8080']):
    src += ['lcd_st7789_240_8080.c']
if GetDepend(['CONFIG_REALTEK_ST7789_320240_8080']):
    src += ['lcd_st7789_320_240_8080.c']

CPPPATH = [cwd]

group = DefineGroup('lcd_low_driver', src, depend = [''], CPPPATH = CPPPATH)
# print(src)
# print(group)

Return('group')