Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()

src = Split("""
""")

if GetDepend(['CONFIG_REALTEK_BSP_PIN']) or GetDepend(['CONFIG_REALTEK_BSP_GPIO']):
    if GetDepend(['CONFIG_REALTEK_BSP_KEY_BUTTON']):
        src += ['key_button_8772f.c']

CPPPATH = [cwd]

group = DefineGroup('key_button', src, depend = ['CONFIG_REALTEK_8772F_DEVICE'], CPPPATH = CPPPATH)

Return('group')