

from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")


if GetDepend(['CONFIG_REALTEK_ST77989_240_320']):
    src += ['lcd_st7789_240_spi.c']
if GetDepend(['CONFIG_REALTEK_ST77571_128_128']):
    src += ['lcd_st7571_128_spi.c']

CPPPATH = [cwd]

group = DefineGroup('lcd_low_driver', src, CPPPATH = CPPPATH, depend = [''])
# print(src)
# print(group)

Return('group')