

from building import *

Import('SDK_ROOT')
# Import('RTK_IC_TYPE')

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")
CPPPATH = [cwd]

if GetDepend(['CONFIG_REALTEK_LCD_C05300_390_450_QSPI']):
    src += ['lcd_c05300_390_450_qspi.c']
if GetDepend(['CONFIG_REALTEK_LCD_SH8601Z_410_502_QSPI']):
    src += ['lcd_sh8601z_410_502_qspi.c']
if GetDepend(['CONFIG_REALTEK_LCD_ST7265_800480_RGB']):
    src += ['lcd_st7265_800480_rgb.c']
if GetDepend(['CONFIG_REALTEK_NV3041A_480_272_QSPI']):
    src += ['nv3041A_480_272_qspi.c']
if GetDepend(['CONFIG_REALTEK_SH8601Z_454454_QSPI']):
    src += ['SH8601Z_454454_qspi.c']
if GetDepend(['CONFIG_REALTEK_ST7701S_480480_RGB']):
    src += ['st7701s_480480_rgb.c']
if GetDepend(['CONFIG_REALTEK_ST77916_360_360_QSPI']):
    src += ['lcd_st77916_360_360_qspi.c']
if GetDepend(['CONFIG_REALTEK_HX8369_480_480_RGB']):
    src += ['hx8369_480480_rgb.c']


group = DefineGroup('lcd_low_driver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')