# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
objs = []

# SOC series to directory prefix mapping
# CONFIG_SOC_SERIES_RTL87X3G -> 8773G, CONFIG_SOC_SERIES_RTL87X3E -> 8773E, etc.
SOC_SERIES_MAP = {
    'CONFIG_SOC_SERIES_RTL87X3G': '8773G',
    'CONFIG_SOC_SERIES_RTL87X3E': '8773E',
    'CONFIG_SOC_SERIES_RTL87X2G': '8762G',
    'CONFIG_SOC_SERIES_RTL87X2F': '8772F',
    'CONFIG_SOC_SERIES_RTL87X2D': '8762D',
    'CONFIG_SOC_SERIES_RTL87X2E': '8762E',
    'CONFIG_SOC_SERIES_RTL87X2H': '8752H',
}

# Device type subdirectories and their config suffix
# CONFIG_REALTEK_8773G_DEVICE_LCD -> lcd/8773G, CONFIG_REALTEK_8773G_DEVICE_KNOB -> knob/8773E, etc.
DEVICE_TYPES = ['lcd', 'touch', 'knob', 'key_button']

for soc_config, chip_dir in SOC_SERIES_MAP.items():
    if GetDepend([soc_config]):
        for dev_type in DEVICE_TYPES:
            # e.g. CONFIG_REALTEK_8773G_DEVICE_LCD
            dev_config = 'CONFIG_REALTEK_' + chip_dir + '_DEVICE_' + dev_type.upper()
            sconscript = os.path.join(cwd, 'general', dev_type, chip_dir, 'SConscript')
            if GetDepend([dev_config]) and os.path.isfile(sconscript):
                objs = objs + SConscript(os.path.join('general', dev_type, chip_dir, 'SConscript'))

Return('objs')
